version: "3.1"

services:
  api:
    container_name: TopicSearch
    restart: always
    build:
      context: ./     
    ports:
      - 5000:80
    networks:
      - pk-network  
    links:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    ports:
      - 49161:9200
    networks:
      - pk-network
    environment:
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=tpicap123

networks:
  pk-network:
    driver: bridge
