version: "3.1"

services:
  api:
    container_name: topicsearch
    restart: always
    build:
      context: ./
    ports:
      - 49162:80
    networks:
      - pk-network
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    restart: always
    ports:
      - 49161:9200
      - 49160:9300
    networks:
      - pk-network
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=tpicap123

networks:
  pk-network:
    driver: bridge
